# _*_ mode: ruby _*_
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
# General Vagrant VM configuration 
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :vmware_fusion do |v|
    v.memory = 256
    v.linked_clone = true
  end 
  
  # Application server 1
  config.vm.define "app01" do |app|
    app.vm.hostname = "app1.dev"
    app.vm.network :private_network, ip: "192.168.60.4"
  end 
  
  # Application server 2
  config.vm.define "app02" do |app|
    app.vm.hostname = "app2.dev"
    app.vm.network :private_network, ip: "192.168.60.5"
  end 
  
  # Database server
  config.vm.define "db" do |db|
    db.vm.hostname = "db.dev"
    db.vm.network :private_network, ip: "192.168.60.6"
  end 
end
  
