# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "centos/7"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
 (1..NODE_COUNT).each do |i|
    config.vm.define "mngr#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "mngr#{i}"
      subconfig.vm.network "private_network", ip: "192.168.30.#{i+2}"

      subconfig.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
      end    
    end
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network "private_network", ip: "192.168.40.#{i+2}"
      subconfig.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
      end  
    end
  end

  # Install docker on all machines  
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y docker && sudo systemctl enable docker && sudo systemctl start docker
  SHELL
end
